# Generated by Django 4.1.3 on 2023-02-22 17:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='games',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('C', 'Cricket'), ('F', 'Football'), ('A', 'All')], default='A', max_length=5),
        ),
    ]
