# Generated by Django 4.1.3 on 2023-03-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(null=True, verbose_name='Date in ( MM/DD/YYYY )'),
        ),
    ]
