# Generated by Django 4.1.3 on 2022-12-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_accounts_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
