# Generated by Django 4.1.3 on 2023-02-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='games',
            field=models.CharField(choices=[('C', 'Cricket'), ('F', 'Football'), ('A', 'All')], default='A', max_length=5),
        ),
    ]
