# Generated by Django 4.1.3 on 2022-12-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_accounts_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterField(
            model_name='accounts',
            name='DOB',
            field=models.DateField(blank=True, null=True, verbose_name='Date in ( MM/DD/YYYY )'),
        ),
    ]
