# Generated by Django 4.1.3 on 2022-12-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_accounts_options_alter_accounts_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='DOB',
            field=models.DateField(blank=True, default=0, null=True, verbose_name='Date in ( MM/DD/YYYY )'),
        ),
    ]
