# Generated by Django 4.1.3 on 2022-12-09 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_accounts_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='DOB',
            field=models.DateField(blank=True, null=True, verbose_name='Date in ( MM/DD/YYYY )'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.CharField(choices=[('C', 'Cricket'), ('F', 'Football'), ('G', 'General')], default='G', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
