# Generated by Django 4.1.3 on 2022-12-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_accounts_dob_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateField(blank=True, null=True, verbose_name='Date in ( MM/DD/YYYY )'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='games',
            field=models.CharField(choices=[('C', 'Cricket'), ('F', 'Football'), ('G', 'General')], default='G', max_length=20),
        ),
    ]
