# Generated by Django 4.1.3 on 2022-12-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CricketPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='cricket_posts')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(max_length=500)),
                ('likes', models.IntegerField(default=0, null=True)),
                ('dislikes', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
