# Generated by Django 4.1.3 on 2023-01-10 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketClubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=90, null=True)),
                ('district', models.CharField(blank=True, choices=[('AL', 'Alappuzha'), ('ER', 'Ernakulam'), ('ID', 'Idukki'), ('KN', 'Kannur'), ('KS', 'Kasaragod'), ('KL', 'Kollam'), ('KT', 'Kottayam'), ('KZ', 'Kozhikode'), ('MA', 'Malapuram'), ('PL', 'Palakkad'), ('PT', 'Pathanmthitta'), ('TV', 'Thiruvanathapuram'), ('TS', 'Thirssur'), ('WA', 'Wayanad')], max_length=30, null=True)),
                ('members', models.ManyToManyField(blank=True, error_messages={'max-limit': 'max of 35 members'}, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CricketPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='cricket_posts')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('context', models.CharField(blank=True, choices=[('C', 'Cricket'), ('G', 'General')], max_length=2, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cricket post',
                'verbose_name_plural': 'cricket posts',
            },
        ),
        migrations.CreateModel(
            name='HostCricketTournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(blank=True, max_length=70, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='CricketTournaments')),
                ('district', models.CharField(blank=True, choices=[('AL', 'Alappuzha'), ('ER', 'Ernakulam'), ('ID', 'Idukki'), ('KN', 'Kannur'), ('KS', 'Kasaragod'), ('KL', 'Kollam'), ('KT', 'Kottayam'), ('KZ', 'Kozhikode'), ('MA', 'Malapuram'), ('PL', 'Palakkad'), ('PT', 'Pathanmthitta'), ('TV', 'Thiruvanathapuram'), ('TS', 'Thirssur'), ('WA', 'Wayanad')], max_length=2, null=True)),
                ('venue', models.CharField(blank=True, max_length=70, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('limit_participants', models.IntegerField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamsRegistered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_teams', models.ManyToManyField(related_name='clubs', to='cricket.cricketclubs')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cricket.hostcrickettournaments')),
            ],
        ),
        migrations.CreateModel(
            name='PostFuntions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.IntegerField(choices=[(0, 'NONE'), (1, 'This post is not related to cricket'), (2, 'Content of the this particular post is abusive'), (3, 'Sexual Content '), (4, 'Others')], default=0)),
                ('dislike', models.ManyToManyField(blank=True, related_name='dislike', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('post_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cricket.cricketposts')),
            ],
            options={
                'verbose_name_plural': 'post funtions',
            },
        ),
    ]
