# Generated by Django 4.1.3 on 2022-12-14 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='cricket_posts')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cricket post',
                'verbose_name_plural': 'cricket posts',
            },
        ),
        migrations.CreateModel(
            name='Post_Funtions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cricket.cricketposts')),
            ],
        ),
    ]
