# Generated by Django 4.1.3 on 2023-02-25 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament_Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.hostcrickettournaments')),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
