# Generated by Django 4.1.3 on 2022-12-15 06:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cricket', '0002_post_funtions_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Funtions',
            new_name='PostFuntions',
        ),
    ]
