# Generated by Django 4.1.3 on 2022-12-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_alter_cricketposts_options_cricketposts_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketposts',
            name='report',
            field=models.CharField(choices=[('OFF TOPIC', 'NOT RELATED TO CRICKET'), ('NOT ALLOWED', 'NOT ALLOWED')], default=None, max_length=30),
        ),
    ]
