# Generated by Django 4.1.3 on 2022-12-15 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cricket', '0003_rename_post_funtions_postfuntions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfuntions',
            options={'verbose_name_plural': 'post funtions'},
        ),
        migrations.AddField(
            model_name='postfuntions',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postfuntions',
            name='report',
            field=models.CharField(choices=[('NOT RELATED TO CRICKET', 'This post is not related to cricket'), ('CONTENT OF THE POST IS ABUSIVE', 'Content of the this particualr post is abusive'), ('SEXUAL CONTENT', 'Sexual Content '), ('OTHERS', 'Others'), ('NONE', 'None')], default='NONE', max_length=60),
        ),
    ]
