# Generated by Django 4.1.3 on 2023-02-25 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('cricket', '0003_tournament_reports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament_reports',
            options={'verbose_name_plural': 'Reports'},
        ),
        migrations.CreateModel(
            name='Resgister_Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.ManyToManyField(blank=True, related_name='registered', to='clubs.clubs')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cricket.hostcrickettournaments')),
            ],
            options={
                'verbose_name_plural': 'Registered Teams',
            },
        ),
    ]
