# Generated by Django 4.1.3 on 2022-12-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_alter_cricketposts_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketposts',
            name='report',
            field=models.CharField(blank=True, choices=[('OFF TOPIC', 'NOT RELATED TO CRICKET'), ('NOT ALLOWED', 'NOT ALLOWED')], max_length=30, null=True),
        ),
    ]
