# Generated by Django 4.1.3 on 2022-12-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0004_alter_postfuntions_options_postfuntions_dislike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfuntions',
            name='report',
            field=models.CharField(choices=[(1, 'This post is not related to cricket'), (2, 'Content of the this particualr post is abusive'), (3, 'Sexual Content '), (4, 'Others'), (0, 'None')], default=0, max_length=60),
        ),
    ]
