# Generated by Django 4.1.3 on 2023-03-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_remove_clubhistoryperuser_club_admin_of'),
        ('cricket', '0004_alter_tournament_reports_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('team_won', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.hostcrickettournaments')),
            ],
        ),
    ]
