# Generated by Django 4.1.3 on 2023-03-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0005_tournamentresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentresult',
            options={'verbose_name_plural': 'Tounament Results'},
        ),
    ]
