# Generated by Django 4.1.3 on 2022-12-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0005_alter_cricketposts_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cricketposts',
            name='report',
        ),
    ]
