# Generated by Django 4.1.3 on 2023-03-11 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_remove_clubhistoryperuser_club_admin_of'),
        ('cricket', '0006_alter_tournamentresult_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particiapants', models.ManyToManyField(blank=True, related_name='participants', to='clubs.clubs')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cricket.hostcrickettournaments')),
            ],
            options={
                'verbose_name_plural': 'Participated Teams',
            },
        ),
    ]
