# Generated by Django 4.1.3 on 2023-03-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0007_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='particiapants',
            new_name='participants',
        ),
    ]
