# Generated by Django 4.1.3 on 2022-12-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0010_alter_postfuntions_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfuntions',
            name='report',
            field=models.CharField(choices=[('ok', 'This post is not related to cricket'), ('ok', 'Content of the this particualr post is abusive'), ('ok', 'Sexual Content '), ('ok', 'Others'), ('ok', 'NONE')], default='ok', max_length=60),
        ),
    ]
