# Generated by Django 4.1.3 on 2022-12-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0011_alter_postfuntions_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfuntions',
            name='report',
            field=models.CharField(choices=[(0, 'NONE'), (1, 'This post is not related to cricket'), (2, 'Content of the this particualr post is abusive'), (3, 'Sexual Content '), (4, 'Others')], default=0, max_length=60),
        ),
    ]
