# Generated by Django 4.1.3 on 2022-12-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0013_alter_postfuntions_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfuntions',
            name='report',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'This post is not related to cricket'), (2, 'Content of the this particular post is abusive'), (3, 'Sexual Content '), (4, 'Others')], default=0),
        ),
    ]
