# Generated by Django 4.1.3 on 2022-12-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0014_alter_postfuntions_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketposts',
            name='context',
            field=models.CharField(blank=True, choices=[('C', 'Cricket'), ('F', 'Football')], max_length=2, null=True),
        ),
    ]
