# Generated by Django 4.1.3 on 2022-12-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0015_cricketposts_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketposts',
            name='context',
            field=models.CharField(blank=True, choices=[('C', 'Cricket'), ('G', 'General')], max_length=2, null=True),
        ),
    ]
