# Generated by Django 4.1.3 on 2023-01-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0017_hostcrickettournaments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostcrickettournaments',
            name='state',
            field=models.CharField(blank=True, choices=[('KR', 'Kerala'), ('TN', 'Tamil Nadu')], max_length=2, null=True),
        ),
    ]
