# Generated by Django 4.1.3 on 2023-01-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0018_alter_hostcrickettournaments_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostcrickettournaments',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alappuzha'), ('ER', 'Ernakulam'), ('ID', 'Idukki'), ('KN', 'Kannur'), ('KS', 'Kasaragod'), ('KL', 'Kollam'), ('KT', 'Kottayam'), ('KZ', 'Kozhikode'), ('MA', 'Malapuram'), ('PL', 'Palakkad'), ('PT', 'Pathanmthitta'), ('TV', 'Thiruvanathapuram'), ('TS', 'Thirssur'), ('WA', 'Wayanad')], max_length=2, null=True),
        ),
    ]
