# Generated by Django 4.1.3 on 2023-01-05 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cricket', '0020_rename_state_hostcrickettournaments_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketclubs',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
