# Generated by Django 4.1.3 on 2023-01-08 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cricket', '0023_alter_cricketclubs_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketclubs',
            name='district',
            field=models.CharField(blank=True, choices=[('AL', 'Alappuzha'), ('ER', 'Ernakulam'), ('ID', 'Idukki'), ('KN', 'Kannur'), ('KS', 'Kasaragod'), ('KL', 'Kollam'), ('KT', 'Kottayam'), ('KZ', 'Kozhikode'), ('MA', 'Malapuram'), ('PL', 'Palakkad'), ('PT', 'Pathanmthitta'), ('TV', 'Thiruvanathapuram'), ('TS', 'Thirssur'), ('WA', 'Wayanad')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hostcrickettournaments',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostcrickettournaments',
            name='limit_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cricketclubs',
            name='members',
            field=models.ManyToManyField(blank=True, error_messages={'max-limit': 'max of 35 members'}, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TeamsRegistered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_teams', models.ManyToManyField(related_name='clubs', to='cricket.cricketclubs')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cricket.hostcrickettournaments')),
            ],
        ),
    ]
