# Generated by Django 4.1.3 on 2022-12-28 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='football_posts')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('context', models.CharField(blank=True, choices=[('C', 'Football'), ('G', 'General')], max_length=2, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'football post',
                'verbose_name_plural': 'football posts',
            },
        ),
    ]
