# Generated by Django 4.1.3 on 2023-01-10 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='football_posts')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('context', models.CharField(blank=True, choices=[('F', 'Football'), ('G', 'General')], max_length=2, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'football post',
                'verbose_name_plural': 'football posts',
            },
        ),
        migrations.CreateModel(
            name='PostFuntions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.IntegerField(choices=[(0, 'NONE'), (1, 'This post is not related to cricket'), (2, 'Content of the this particular post is abusive'), (3, 'Sexual Content '), (4, 'Others')], default=0)),
                ('dislike', models.ManyToManyField(blank=True, related_name='football_dislike', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='football_likes', to=settings.AUTH_USER_MODEL)),
                ('post_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='football.footballposts')),
            ],
            options={
                'verbose_name_plural': 'post funtions',
            },
        ),
    ]
