# Generated by Django 4.1.3 on 2022-12-28 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFuntions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.IntegerField(choices=[(0, 'NONE'), (1, 'This post is not related to cricket'), (2, 'Content of the this particular post is abusive'), (3, 'Sexual Content '), (4, 'Others')], default=0)),
                ('dislike', models.ManyToManyField(blank=True, related_name='football_dislike', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='football_likes', to=settings.AUTH_USER_MODEL)),
                ('post_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='football.footballposts')),
            ],
            options={
                'verbose_name_plural': 'post funtions',
            },
        ),
    ]
