# Generated by Django 4.1.3 on 2023-02-27 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0002_clubhistoryperuser_club_admin_of'),
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostFootballTournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(blank=True, max_length=70, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='FootballTournaments')),
                ('district', models.CharField(blank=True, choices=[('AL', 'Alappuzha'), ('ER', 'Ernakulam'), ('ID', 'Idukki'), ('KN', 'Kannur'), ('KS', 'Kasaragod'), ('KL', 'Kollam'), ('KT', 'Kottayam'), ('KZ', 'Kozhikode'), ('MA', 'Malapuram'), ('PL', 'Palakkad'), ('PT', 'Pathanmthitta'), ('TV', 'Thiruvanathapuram'), ('TS', 'Thirssur'), ('WA', 'Wayanad')], max_length=2, null=True)),
                ('venue', models.CharField(blank=True, max_length=70, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(null=True)),
                ('limit_participants', models.IntegerField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=600, null=True)),
                ('end_registration', models.DateField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registered_teams', models.ManyToManyField(blank=True, related_name='RegisteredForFootball', to='clubs.clubs')),
            ],
            options={
                'verbose_name': 'Football Tournament',
                'verbose_name_plural': 'Football Tournaments',
            },
        ),
        migrations.CreateModel(
            name='Resgister_Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.ManyToManyField(blank=True, related_name='registered_Football', to='clubs.clubs')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football.hostfootballtournaments')),
            ],
            options={
                'verbose_name_plural': 'Registered Teams',
            },
        ),
        migrations.CreateModel(
            name='Tournament_Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.hostfootballtournaments')),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Tournament_Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporters', models.ManyToManyField(blank=True, related_name='reporters_Football', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='football.hostfootballtournaments')),
            ],
            options={
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.RemoveField(
            model_name='postfuntions',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='postfuntions',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='postfuntions',
            name='post_id',
        ),
        migrations.DeleteModel(
            name='FootballPosts',
        ),
        migrations.DeleteModel(
            name='PostFuntions',
        ),
    ]
