# Generated by Django 4.1.3 on 2023-03-15 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_remove_clubhistoryperuser_club_admin_of'),
        ('football', '0002_hostfootballtournaments_resgister_tournaments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.ManyToManyField(blank=True, related_name='participants_football', to='clubs.clubs')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football.hostfootballtournaments')),
            ],
            options={
                'verbose_name_plural': 'Participated Teams Football',
            },
        ),
        migrations.CreateModel(
            name='FootballTournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.hostfootballtournaments')),
                ('won', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
            ],
            options={
                'verbose_name_plural': 'Football Tounament Results',
            },
        ),
    ]
