# Generated by Django 4.1.3 on 2022-12-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_alter_footballposts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballposts',
            name='context',
            field=models.CharField(blank=True, choices=[('F', 'Football'), ('G', 'General')], max_length=2, null=True),
        ),
    ]
