# Generated by Django 4.1.3 on 2023-03-03 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0002_hostfootballtournaments_resgister_tournaments_and_more'),
        ('clubs', '0003_remove_clubhistoryperuser_club_admin_of'),
        ('cricket', '0004_alter_tournament_reports_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'STATUS',
            },
        ),
        migrations.CreateModel(
            name='ClubFootballMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('players', models.ManyToManyField(blank=True, related_name='football_players', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.hostfootballtournaments')),
            ],
            options={
                'verbose_name_plural': 'Football Members',
            },
        ),
        migrations.CreateModel(
            name='ClubCricketMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('players', models.ManyToManyField(blank=True, related_name='cricket_players', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.hostcrickettournaments')),
            ],
            options={
                'verbose_name_plural': 'Cricket Members',
            },
        ),
    ]
