# Generated by Django 4.1.3 on 2023-03-03 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_remove_clubhistoryperuser_club_admin_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0002_hostfootballtournaments_resgister_tournaments_and_more'),
        ('cricket', '0004_alter_tournament_reports_options_and_more'),
        ('team_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberstatus',
            options={'verbose_name_plural': ' MEMBER STATUS'},
        ),
        migrations.CreateModel(
            name='MemberTournamentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Member Status Per Tournament',
            },
        ),
        migrations.CreateModel(
            name='ClubRegisteredFootballTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('tournament', models.ManyToManyField(blank=True, to='cricket.hostcrickettournaments')),
            ],
            options={
                'verbose_name_plural': 'Registered Tournaments Per Club',
            },
        ),
        migrations.CreateModel(
            name='ClubRegisteredCricketTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('tournament', models.ManyToManyField(blank=True, to='cricket.hostcrickettournaments')),
            ],
            options={
                'verbose_name_plural': 'Registered Tournaments Per Club',
            },
        ),
        migrations.CreateModel(
            name='Club_Games_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('cricket_registed', models.ManyToManyField(blank=True, related_name='cricket_registered', to='cricket.hostcrickettournaments')),
                ('cricket_tournaments_won', models.ManyToManyField(blank=True, related_name='cricket_won', to='cricket.hostcrickettournaments')),
                ('football_registered', models.ManyToManyField(blank=True, related_name='football_registered', to='football.hostfootballtournaments')),
                ('football_tournaments_won', models.ManyToManyField(blank=True, related_name='football_won', to='football.hostfootballtournaments')),
                ('participated_cricket', models.ManyToManyField(blank=True, related_name='cricket_participated', to='cricket.hostcrickettournaments')),
                ('participated_football', models.ManyToManyField(blank=True, related_name='football_participated', to='football.hostfootballtournaments')),
            ],
            options={
                'verbose_name_plural': 'Club History',
            },
        ),
    ]
