# Generated by Django 4.1.3 on 2023-03-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0003_delete_membertournamentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubregisteredfootballtournament',
            name='club',
        ),
        migrations.RemoveField(
            model_name='clubregisteredfootballtournament',
            name='tournament',
        ),
        migrations.RenameField(
            model_name='club_games_history',
            old_name='cricket_registed',
            new_name='cricket_registered',
        ),
        migrations.DeleteModel(
            name='ClubRegisteredCricketTournament',
        ),
        migrations.DeleteModel(
            name='ClubRegisteredFootballTournament',
        ),
    ]
