# Generated by Django 4.1.3 on 2023-02-23 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubowner',
            options={'verbose_name_plural': 'Club and Owners'},
        ),
        migrations.AlterField(
            model_name='clubs',
            name='district',
            field=models.CharField(choices=[('AL', 'Alappuzha'), ('ER', 'Ernakulam'), ('ID', 'Idukki'), ('KN', 'Kannur'), ('KS', 'Kasaragod'), ('KL', 'Kollam'), ('KT', 'Kottayam'), ('KZ', 'Kozhikode'), ('MA', 'Malapuram'), ('PL', 'Palakkad'), ('PT', 'Pathanmthitta'), ('TV', 'Thiruvanathapuram'), ('TS', 'Thirssur'), ('WA', 'Wayanad')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='games',
            field=models.CharField(choices=[('C', 'Cricket'), ('F', 'Football'), ('A', 'All')], max_length=2),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='name',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
