# Generated by Django 4.1.3 on 2023-02-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='games',
            field=models.CharField(blank=True, choices=[('C', 'Cricket'), ('F', 'Football'), ('A', 'All')], max_length=2),
        ),
    ]
