# Generated by Django 4.1.3 on 2023-03-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubhistoryperuser_club_admin_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubhistoryperuser',
            name='club_admin_of',
        ),
    ]
