# Generated by Django 4.1.3 on 2023-02-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_clubs_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clubs logos'),
        ),
    ]
