# Generated by Django 4.1.3 on 2023-02-03 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0003_clubs_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('clubAdmins', models.ManyToManyField(blank=True, related_name='Club_Admins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
