# Generated by Django 4.1.3 on 2023-02-23 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_clubowner_club_alter_clubowner_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=90),
            preserve_default=False,
        ),
    ]
