# Generated by Django 4.1.3 on 2023-02-23 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0005_alter_clubowner_club_alter_clubowner_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubowner',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs'),
        ),
        migrations.AlterField(
            model_name='clubowner',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
