# Generated by Django 4.1.3 on 2023-02-14 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0005_alter_clubadmins_options_memebershiprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memebershiprequest',
            name='sender',
        ),
        migrations.AddField(
            model_name='memebershiprequest',
            name='sender',
            field=models.ManyToManyField(blank=True, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
