# Generated by Django 4.1.3 on 2023-02-15 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0006_remove_memebershiprequest_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memebershiprequest',
            name='sender',
        ),
        migrations.CreateModel(
            name='MembershipResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.ManyToManyField(blank=True, related_name='accepted', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('declined', models.ManyToManyField(blank=True, related_name='declined', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='memebershiprequest',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
