# Generated by Django 4.1.3 on 2023-02-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_clubowner_club_alter_clubowner_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubOwner',
        ),
    ]
