# Generated by Django 4.1.3 on 2023-02-15 06:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0007_remove_memebershiprequest_sender_membershipresponses_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemebershipRequest',
            new_name='MembershipRequest',
        ),
        migrations.AlterModelOptions(
            name='membershipresponses',
            options={'verbose_name_plural': 'Membership Responses'},
        ),
    ]
