# Generated by Django 4.1.3 on 2023-02-15 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0008_rename_memebershiprequest_membershiprequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipresponses',
            name='waiting',
            field=models.ManyToManyField(blank=True, related_name='waiting', to=settings.AUTH_USER_MODEL),
        ),
    ]
