# Generated by Django 4.1.3 on 2023-02-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_remove_membershipresponses_declined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubs',
            options={},
        ),
        migrations.AddField(
            model_name='clubadmins',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
