# Generated by Django 4.1.3 on 2023-02-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_alter_clubs_options_clubadmins_time_stamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubs',
            options={'verbose_name_plural': 'Clubs'},
        ),
    ]
