# Generated by Django 4.1.3 on 2023-02-19 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0012_alter_clubs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
